import {
  FormConfig,
  FieldType,
  DropdownOption,
} from "@/components/DynamicForm";

// Cấu hình form thêm đồ dùng
export const ITEM_FORM_CONFIG: FormConfig = {
  title: "Thêm đồ dùng",
  saveButtonTitle: "Lưu",
  fields: [
    {
      name: "image",
      type: FieldType.IMAGE,
      label: "Thêm ảnh",
      width: "100%",
    },
    {
      name: "name",
      type: FieldType.TEXT,
      label: "Tên đồ dùng",
      placeholder: "Nhập tên đồ dùng",
      required: true,
      width: "100%",
    },
    {
      name: "category",
      type: FieldType.DROPDOWN,
      label: "Danh mục",
      required: true,
      options: [
        { label: "Chọn danh mục", value: "" },
        { label: "Đồ điện tử", value: "electronic" },
        { label: "Đồ nội thất", value: "furniture" },
        { label: "Thiết bị nhà bếp", value: "kitchen" },
        { label: "Quần áo", value: "clothes" },
        { label: "Khác", value: "others" },
      ],
      width: "100%",
    },
    {
      name: "purchaseDate",
      type: FieldType.DATE,
      label: "Ngày mua",
      width: "48%",
    },
    {
      name: "warrantyExpirationDate",
      type: FieldType.DATE,
      label: "Hết hạn bảo hành",
      width: "48%",
    },
    {
      name: "location",
      type: FieldType.DROPDOWN,
      label: "Vị trí",
      options: [
        { label: "Chọn vị trí", value: "" },
        { label: "Phòng khách", value: "living_room" },
        { label: "Phòng ngủ", value: "bedroom" },
        { label: "Nhà bếp", value: "kitchen" },
        { label: "Phòng tắm", value: "bathroom" },
        { label: "Kho", value: "storage" },
      ],
      width: "100%",
    },
    {
      name: "price",
      type: FieldType.NUMBER,
      label: "Giá",
      placeholder: "Nhập giá",
      keyboardType: "numeric",
      width: "100%",
    },
    {
      name: "quantity",
      type: FieldType.NUMBER,
      label: "Số lượng",
      placeholder: "Nhập số lượng",
      keyboardType: "phone-pad",
      width: "100%",
    },
  ],
};

// Cấu hình form thêm vật nuôi
export const PET_FORM_CONFIG: FormConfig = {
  title: "Thêm vật nuôi",
  saveButtonTitle: "Lưu",
  fields: [
    {
      name: "image",
      type: FieldType.IMAGE,
      label: "Thêm ảnh",
      width: "100%",
    },
    {
      name: "name",
      type: FieldType.TEXT,
      label: "Tên vật nuôi",
      placeholder: "Nhập tên vật nuôi",
      required: true,
      width: "100%",
    },
    {
      name: "species",
      type: FieldType.DROPDOWN,
      label: "Loài",
      options: [
        { label: "Chọn loài", value: "" },
        { label: "Chó", value: "dog" },
        { label: "Mèo", value: "cat" },
        { label: "Chim", value: "bird" },
        { label: "Cá", value: "fish" },
        { label: "Bò sát", value: "reptile" },
        { label: "Khác", value: "other" },
      ],
      width: "100%",
    },
    {
      name: "breed",
      type: FieldType.TEXT,
      label: "Giống",
      placeholder: "Nhập giống vật nuôi",
      width: "100%",
    },
    {
      name: "birthDate",
      type: FieldType.DATE,
      label: "Ngày sinh",
      width: "48%",
    },
    {
      name: "gender",
      type: FieldType.DROPDOWN,
      label: "Giới tính",
      options: [
        { label: "Chọn giới tính", value: "" },
        { label: "Đực", value: "male" },
        { label: "Cái", value: "female" },
      ],
      width: "48%",
    },
    {
      name: "weight",
      type: FieldType.NUMBER,
      label: "Cân nặng (kg)",
      placeholder: "Nhập cân nặng",
      keyboardType: "numeric",
      width: "100%",
    },
    {
      name: "nextVaccineDate",
      type: FieldType.DATE,
      label: "Tiêm vaccine tiếp theo",
      width: "48%",
    },
    {
      name: "nextCheckupDate",
      type: FieldType.DATE,
      label: "Khám bệnh tiếp theo",
      width: "48%",
    },
    {
      name: "spayedNeutered",
      type: FieldType.DROPDOWN,
      label: "Tình trạng thiến/triệt sản",
      options: [
        { label: "Chọn tình trạng", value: "" },
        { label: "Đã thiến/triệt sản", value: "yes" },
        { label: "Chưa thiến/triệt sản", value: "no" },
        { label: "Không áp dụng", value: "na" },
      ],
      width: "100%",
    },
    {
      name: "feedingFrequency",
      type: FieldType.DROPDOWN,
      label: "Tần suất cho ăn",
      options: [
        { label: "Chọn tần suất", value: "" },
        { label: "Ngày 1 lần", value: "once_day" },
        { label: "Ngày 2 lần", value: "twice_day" },
        { label: "Ngày 3 lần", value: "thrice_day" },
        { label: "Tự do", value: "free" },
      ],
      width: "100%",
    },
    {
      name: "notes",
      type: FieldType.TEXTAREA,
      label: "Ghi chú",
      placeholder: "Nhập ghi chú về thú cưng",
      numberOfLines: 4,
      width: "100%",
    },
  ],
};

// Cấu hình form thêm cây cối
export const PLANT_FORM_CONFIG: FormConfig = {
  title: "Thêm cây cối",
  saveButtonTitle: "Lưu",
  fields: [
    {
      name: "image",
      type: FieldType.IMAGE,
      label: "Thêm ảnh",
      width: "100%",
    },
    {
      name: "name",
      type: FieldType.TEXT,
      label: "Tên cây",
      placeholder: "Nhập tên cây",
      required: true,
      width: "100%",
    },
    {
      name: "species",
      type: FieldType.TEXT,
      label: "Loài",
      placeholder: "Nhập loài cây",
      width: "100%",
    },
    {
      name: "acquiredDate",
      type: FieldType.DATE,
      label: "Ngày nhận cây",
      width: "48%",
    },
    {
      name: "location",
      type: FieldType.DROPDOWN,
      label: "Vị trí",
      options: [
        { label: "Chọn vị trí", value: "" },
        { label: "Phòng khách", value: "living_room" },
        { label: "Ban công", value: "balcony" },
        { label: "Sân vườn", value: "garden" },
        { label: "Phòng ngủ", value: "bedroom" },
        { label: "Nhà bếp", value: "kitchen" },
        { label: "Khác", value: "other" },
      ],
      width: "48%",
    },
    {
      name: "wateringFrequency",
      type: FieldType.DROPDOWN,
      label: "Tần suất tưới nước",
      options: [
        { label: "Chọn tần suất", value: "" },
        { label: "Hàng ngày", value: "daily" },
        { label: "2-3 ngày/lần", value: "2_3_days" },
        { label: "Hàng tuần", value: "weekly" },
        { label: "2 tuần/lần", value: "biweekly" },
        { label: "Hàng tháng", value: "monthly" },
      ],
      width: "100%",
    },
    {
      name: "lastWateredDate",
      type: FieldType.DATE,
      label: "Lần tưới gần nhất",
      width: "48%",
    },
    {
      name: "nextWateringDate",
      type: FieldType.DATE,
      label: "Lần tưới tiếp theo",
      width: "48%",
    },
    {
      name: "lastFertilizedDate",
      type: FieldType.DATE,
      label: "Lần bón phân gần nhất",
      width: "48%",
    },
    {
      name: "nextFertilizingDate",
      type: FieldType.DATE,
      label: "Lần bón phân tiếp theo",
      width: "48%",
    },
    {
      name: "lightRequirement",
      type: FieldType.DROPDOWN,
      label: "Nhu cầu ánh sáng",
      options: [
        { label: "Chọn nhu cầu ánh sáng", value: "" },
        { label: "Ánh sáng trực tiếp", value: "full_sun" },
        { label: "Ánh sáng gián tiếp", value: "indirect_light" },
        { label: "Bóng râm từng phần", value: "partial_shade" },
        { label: "Bóng râm hoàn toàn", value: "full_shade" },
      ],
      width: "100%",
    },
    {
      name: "notes",
      type: FieldType.TEXTAREA,
      label: "Ghi chú",
      placeholder: "Nhập ghi chú về cây",
      numberOfLines: 4,
      width: "100%",
    },
  ],
};
